AllCops:
  TargetRubyVersion: 3.2

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - 'cieye.gemspec'

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false